---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: app
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.31.0
  values:
    controller:
      service:
        type: LoadBalancer
